### ISSUE TITLE
Various issues

### ISSUE THREAD

**Issue by zbeekman** [radiasoft/container-beamsim-part1#2]
- It appears that the CI tests are failing. Is this an issue?
- Is there a docker file somewhere? The build process is rather obfuscated. I am trying to install [taucmdr] in this image at runtime, but it needs cURL or wget. sudo doesn't seem to work
- It would be great to install taucmdr into a docker image hosted in a registry so we can generate a complete configuration (time consuming build) and then just pull that image to start testing. In fact, if I can figure out how to run as root during a docker build based on beamsim-part1, I may push my own docker image extending beamsim-part1.

[taucmdr]: https://github.com/ParaToolsInc/taucmdr

**Comment by robnagler** [comment]
The last failure I see is https://travis-ci.org/radiasoft/zgoubi/builds/411441871 which was 13 days ago. Did you restart the build? That wipes the history. Better to trigger a new build.

We try to be container-platform neutral with our build process so Dockefiles and Vagrantfiles are dynamically generated  and as short as possible and our build scripts are reusable. We have very different goals, including reproducibility and testability. Our simplification is to define small recipes to build "codes", which can be [found in download/installers/codes](https://github.com/radiasoft/download/tree/master/installers/code/codes).

We do not like building as root. This is dangerous even in a container. If you have an rpm for F27, we can install that in beamsim-part1 with a build script, see [elegant.sh for an example](https://github.com/radiasoft/download/blob/master/installers/code/codes/elegant.sh). During the build, sudo is available, but it is removed before the container is committed.

What we do is build within `/home/vagrant/src/radiasoft/codes and install` at `$(pyenv prefix)`. We try to structure the builds so that `rsmanifest.json` is always updated so we can document provenance. Again, our focus is on reproducibility, not on making containers small and lightweight.

If you give me the recipe to build taucmdr, I can add it to our list of codes and then add it to beamsim-part1. That way anybody using our vagrant-dev environment can install it with:

```sh
radia_run code taucmdr
```

**Comment by zbeekman** [comment]
> The last failure I see is travis-ci.org/radiasoft/zgoubi/builds/411441871 which was 13 days ago. Did you restart the build? That wipes the history. Better to trigger a new build.

I didn't realize that I had permissions to enable me to restart... just restarted it! Thanks!



> We try to be container-platform neutral with our build process so Dockefiles and Vagrantfiles are dynamically generated and as short as possible and our build scripts are reusable. We have very different goals, including reproducibility and testability. Our simplification is to define small recipes to build "codes", which can be found in download/installers/codes.

OK, I'll have a look and see if that increases my understanding of how the process works.

> We do not like building as root. This is dangerous even in a container. If you have an rpm for F27, we can install that in beamsim-part1 with a build script, see elegant.sh for an example. During the build, sudo is available, but it is removed before the container is committed.

TAU Commander does not need to be root to be installed. In fact, for multi-user systems, the preferred method is to install into the user's home directory. 

However, in beamsim-part1 I was encountering strange issues while trying to install TAU Commander and configure a TAU Commander project. First the TAU Commander makefile seemed to be getting /bin/sh whereas on most systems I've used it on, it seemed to be /bin/bash. (Commands like `$(shell which curl)` were failing in the Makefile.) Then during project initialization, it was complaining that it could not find g++. Finally, during project initialization it failed to launch a download of various assets using curl. I worked through each of the issues in the prototype script I have except for the last one.

TAU Commander also is picky about reproducibility, so it downloads and uses its own miniconda based python environment.

> What we do is build within /home/vagrant/src/radiasoft/codes and install at $(pyenv prefix). We try to structure the builds so that rsmanifest.json is always updated so we can document provenance. Again, our focus is on reproducibility, not on making containers small and lightweight.

Sounds good. My issue with this right now is that I don't understand the control flow/call path across the different repositories.

> If you give me the recipe to build taucmdr, I can add it to our list of codes and then add it to beamsim-part1. That way anybody using our vagrant-dev environment can install it with:
> 
> radia_run code taucmdr

OK. Let me look at download/installers/codes and elegant.sh. If I can understand how, then I will try to extrapolate that to TAU Commander and open a pull request.

Otherwise I'll just give you the formula or a short example script.

One issue (currently) is that we need to get a release out for TAU Commander. I typically use the unstable branch. This is not good for reproducibility etc. If I pinned the install to a specific commit would that be acceptable?

Another potential issue might be the python environments and TAU Commanders usage of it's own private miniconda based environment. I'm not 100% sure what impact this might have on integrating it.

And finally, TAU Commander sometimes will fetch and install additional software into it's own install tree, or at least reconfigure existing software based on the project being instrumented. Different instrumentation options can cause a reconfiguration and recompilation of TAU itself. (This complexity motivated the more abstract commander interface...) This can *mostly* be avoided by running

```
INSTALLDIR/system/configure
```

After `make install` but it will bloat the image substantially. (Another reason why it Commander tries to just use what it needs.)

A work around for this latter issue, might be to pre-configure a TAU Commander for zgoubi during the TAU Commander installation. If all the measurements and targets are setup and selected then, it will trigger all the necessary builds...

I need to experiment to determine the whether, and to what extent, this last issue is actually relevant to our use case.

As far as SOW I goes, I'm going to try running interactively in docker and documenting the steps. I hope this will be sufficient to close out SOW 1, if I can produce profiles and write up a small summary of the results.

**Comment by zbeekman** [comment]
P.S., sorry that last comment is so long... I really appreciate your thoughtful response and you taking the time to help get me up to speed with your infrastructure. Thanks again @robnagler!

**Comment by zbeekman** [comment]
> You have privs on Travis to restart, because you have write privs on GitHub.

:+1: I re-ran the build and it still fails: https://travis-ci.org/radiasoft/container-beamsim-part1/builds/261407867#L1033-L1049

> You don't need to learn how our build process works. It would be easier if you just sent me the instructions on how to build taucmdr.

OK, sounds good. Please see below for instructions.

> shell which curl is not portable in sh afaik. I think it came from csh. For sh/bash, you want to use type, which is defined as a builtin so that it can find aliases and functions, like it does in csh.

I was unaware of the provenance of `which` but I was aware that it isn't portable. I've updated our makefile to be more portable. I think usually `type -P curl` or `command -pv curl` are the most portable options.

> I've often seen which used in build scripts unnecessarily. If you do something like CURL = $(which curl), which is not really doing anything. Rather, just define CURL = curl, and let the shell do the same thing that which is emulating.

Well, for TAU Commander we have to support a host of exotic systems, Cray, SGI/HPX, IBM BGP/BGQ, various linux distros etc. The problem is curl and wget are not guaranteed to be on a system. The invocation of `which` was to select an appropriate download strategy... Perhaps the download should just be tried with one method and if it fails, then the other method tried.

> We definitely don't want miniconda involved. This would be battling with pyenv, which is going to give everybody headaches. Again, I can help with this. Just send me the source/branch you want to build from and the way to run CMake or whatever it uses.

OK, I just did some testing, and it looks like (fingers crossed) I may be able to install the full TAU Commander config without Miniconda in the docker environment. The build is still going, so I'm not 100% sure yet that this works. I'm using the instructions for installing TAU Commander I included above. If you're able to build a docker image with TAU Commander already installed that would be very helpful.

Here are the build instructions for TAU Commander:

```bash
git clone --branch=unstable https://github.com/ParaToolsInc/taucmdr
cd taucmdr
make install USE_MINICONDA=fasle TAU=full INSTALLDIR=$(pyenv prefix)/taucmdr install
$(pyenv prefix)/taucmdr/system/configure # Ensure we have all possible TAU configs
```

FYI, I'm not sure how rigourous the various scripts are about checking the return status, you may encounter issues if you build with `set -euo pipefail`.

If it's possible to make `</path/to/install/location>/taucmdr/system` rwX by the user that compiles zgoubi (`vagrant` I think) that would be nice because it would allow additional configurations to get setup if `.../system/configure` doesn't build them.

I have attached my prototype script:
[profile-tau.sh.prototype.txt](https://github.com/radiasoft/container-beamsim-part1/files/2291649/profile-tau.sh.prototype.txt)


Hopefully with the changes I pushed to TAU Commander, you won't need the `SHELL=/bin/bash` variable when calling `make ... install`.

**Comment by zbeekman** [comment]
FYI, that last prototype script has a serious problem that was probably the source of my woes.... I clobbered $PATH... sigh.

**Comment by robnagler** [comment]
When compiling taucmdr, I see things like: 

```text
An error occurred configuring TAU for experiment v-taucmdr-trace: TAU
```

There's a real error before:

```text
tau2otf2.cpp:1421:12: error: ‘OTF2_Archive_Close’ was not declared in this scope
   status = OTF2_Archive_Close( archive );
            ^~~~~~~~~~~~~~~~~~
make[2]: *** [Makefile:64: tau2otf2.o] Error 1
```

Do I just ignore these?

**Comment by zbeekman** [comment]
Yes that should be fine. Thanks!

**Comment by robnagler** [comment]
Is there a way to get tau to respect $TERM? Here's the output of tau metrics:

```text
ESC[36m== PAPI Preset Metrics on Target 'beamsim-p1' =============================================================================================================================================
ESC[0m
ESC[1mNameESC[0m  ESC[37m|ESC[0m                                                                                     ESC[1mDescriptionESC[0m
ESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m+ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0m
ESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0m
ESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0m
ESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0m

ESC[36m== TAU Metrics on Target 'beamsim-p1' =====================================================================================================================================================
ESC[0m
        ESC[1mNameESC[0m          ESC[37m|ESC[0m                                                                             ESC[1mDescriptionESC[0m
ESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m+ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0m
ESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0m
ESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0m
ESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0mESC[37m=ESC[0m
       CLOCK_GET_TIME ESC[37m|ESC[0m Wall clock that calls clock_gettime.
             CPU_TIME ESC[37m|ESC[0m CPU timer that calls getrusage.
      GET_TIME_OF_DAY ESC[37m|ESC[0m Wall clock that calls gettimeofday.
         LINUX_TIMERS ESC[37m|ESC[0m Linux high resolution wall clock.
        LOGICAL_CLOCK ESC[37m|ESC[0m Logical clock that increments on each request.
         MEMORY_DELTA ESC[37m|ESC[0m Instantaneous resident set size (RSS)
            PAPI_TIME ESC[37m|ESC[0m Alias for P_WALL_CLOCK_TIME.  Wall clock that calls PAPI_get_real_usec.
    PAPI_VIRTUAL_TIME ESC[37m|ESC[0m Alias for P_VIRTUAL_TIME.  PAPI virtual clock that calls PAPI_get_virt_usec.
       P_VIRTUAL_TIME ESC[37m|ESC[0m PAPI virtual clock that calls PAPI_get_virt_usec.
    P_WALL_CLOCK_TIME ESC[37m|ESC[0m Wall clock that calls PAPI_get_real_usec.
 TAU_MPI_MESSAGE_SIZE ESC[37m|ESC[0m Running sum of all MPI messsage sizes.
                 TIME ESC[37m|ESC[0m Alias for GET_TIME_OF_DAY. Wall clock that calls gettimeofday.
           USER_CLOCK ESC[37m|ESC[0m User-defined clock. Implement 'void metric_write_userClock(int tid, double value)'  to set the clock value.
```

**Comment by robnagler** [comment]
This output is to a file `tau metrics > tau.out`

**Comment by zbeekman** [comment]
No, currently, I don't think Commander respects `$TERM`. I'll open an issue. (https://github.com/ParaToolsInc/taucmdr/issues/291) You can get it to stop injecting ANSI escape sequences with `export ANSI_COLORS_DISABLED=1`.

As far as tau metrics goes, this is just showing that we don't have access to any of the hardware counters from inside a docker image. This is probably for security reasons and/or by design from docker's perspective.

However, this means that from within docker it will be impossible to empirically measure things like the L2 cache miss rate (and total hits and misses) fraction of load/store instructions over total instructions, fraction of stalled cycles (waiting on resources, e.g. fetch from RAM) vs total cycles and other useful (CPU architecture specific) hardware counters. To get these we'll probably have to run on bare metal/outside docker.

Come to think of it, I haven't tested in a VM. Since *everything* is virtualized, perhaps HW counter register access is allowed? Is the build process for vagrant/virtual box external to docker? (I.e, a full blown VM)

The current issue I've encountered is issues (probably due to TinyDB) from within a mounted directory. I suspect if I create the TAU Commander project in a directory that only docker has access to then zip it up after execution things may run more smoothly.

**Comment by zbeekman** [comment]
Also, does this mean that there is a new radiasoft/beamsim-part1 image available with the "full" (i.e., minus failed configs) tau install?

**Comment by robnagler** [comment]
Not yet. I am going to create an RPM that we can install. It adds 1.7G without the source directory. 

Am I correct in assuming that I only need to do this:

```sh
make TAU=full USE_MINICONDA=false INSTALLDIR=~/.local/taucmdr install
```

I noticed that taucmdr puts files in ~/.local so I will just put everything there, if that makes sense.

**Comment by zbeekman** [comment]
To be honest, in general, and without vendored miniconda, I have no idea how robust this all will be. But there's only one way to find out.

> I noticed that taucmdr puts files in ~/.local so I will just put everything there, if that makes sense.

I suspect that will be perfect. In general we encourage per-user installations rather than system wide installations. If we ensure that everything in `~/.local` is also `rwX` by `vagrant` (or whatever the $USER is) that would be helpful.

Thanks.

**Comment by robnagler** [comment]
> export ANSI_COLORS_DISABLED=1

Thanks.

> As far as tau metrics goes, this is just showing that we don't have access to any of the hardware counters from inside a docker image.

The output I included was run in VirtualBox so I would think everything would be available.

You can `docker run --cap-add sys_ptrace ...` which should give you enough privs.

> Is the build process for vagrant/virtual box external to docker? 

Yes.

> The current issue I've encountered is issues (probably due to TinyDB) from within a mounted directory. 

What's the error?

**Comment by zbeekman** [comment]
> The output I included was run in VirtualBox so I would think everything would be available.
> 
> You can docker run --cap-add sys_ptrace ... which should give you enough privs.

I'll try that. The HW counters I am looking for are not in the output of your `tau metrics` either. This calls `papi_avail` under the hood. To have metrics besides TIME and various variants of it, you would see entries like `PAPI_L2_DCM`, `PAPI_L2_TCA`, `PAPI_TOT_CYC`, `PAPI_RES_STL`, `PAPI_LS_INS`, etc. Different CPU's provide different hardware counter registers. PAPI is an abstraction over these, with pre-configured metrics that may actually be doing something more sophisticated under the hood.

**Comment by zbeekman** [comment]
Even with `--cap-add=ALL` and `--privileged` there is no access to HW counters on my system. It's possible that docker running natively on a linux box instead of my macOS machine may have different results.


> What's the error?

The error was state corruption. TAU Commander uses file locks, so it's possible that we needed additional capacities to be set to work correctly, like SYS_RAWIO, IPC_LOCK, and/or LEASE. It's also possible that TinyDB is not robust enough with our in-memory caching setup.

**Comment by robnagler** [comment]
@zbeekman is there a way to have the build process for taucmdr inherit `$(MAKE)`? The problem is that the build is using `-j $(nproc)`, and that's not correct for machines with hyperthreading turned on. I want to be able to control the number of CPUs used externally. I could technically do this by restricting the docker container, but I think it would be better for taucmdr make to inherit the `-j` value by using $(MAKE) internally.

**Comment by robnagler** [comment]
You can now install taucmdr into /home/vagrant/.local/taucmdr with:

```sh
yum install -y https://depot.radiasoft.org/foss/rscode-taucmdr-dev.rpm
```

You could install this as an ordinary user with rpm2cpio, but ideally, you'd use yum so that it is managed properly.

**Comment by zbeekman** [comment]
> @zbeekman is there a way to have the build process for taucmdr inherit $(MAKE)? The problem is that the build is using -j $(nproc), and that's not correct for machines with hyperthreading turned on.

Do you think this is causing build failures? Or is just sub-optimal? Or hogging too many resources? (FWIW, probably not much, in my experience my builds typically run fastest when I throw as many threads as possible at them...)

I'll open a TAU Commander issue to track this, and to inherit `$(MAKE)`

> You can now install taucmdr into /home/vagrant/.local/taucmdr with:
> 
> yum install -y https://depot.radiasoft.org/foss/rscode-taucmdr-dev.rpm
> You could install this as an ordinary user with rpm2cpio, but ideally, you'd use yum so that it is managed properly.

OK, so presumably I need sudo or Root to install this? Should it be done through the testing script, or should we create a docker image with it installed already?

**Comment by zbeekman** [comment]
Just curious if I should expect ~750 kB/s download from
https://depot.radiasoft.org/foss/rscode-taucmdr-dev.rpm. My current
connection is ~300Mb/s. Also, I think there are so many small procedures in
zgoubi that one of the reasons our profile was so sparse was throttling.
I'm trying to decrease the throttling threshold to something less than
10ms, to resolve devtra.f etc.

Preliminary results look similar to the profile for the other test case,
lots of time spent in math intrinsics and libgfortran, likely because many
small, short procedures in zgoubi are being throttled by TAU to
reduce/prevent excessive time dilation.

**Comment by robnagler** [comment]
> Do you think this is causing build failures? 

My Mac crashed while taucmdr was compiling. It was really unhappy giving up all that CPU so it gave up completely. :) 

In general, I think the number of threads dedicated to a compile should be decided by the user, not the developer who can't know what else is going on.

Thanks for looking into this.

> OK, so presumably I need sudo or Root to install this?

Yes. 

> Should it be done through the testing script, or should we create a docker image with it installed already?

There's  little to gain in terms of download speed having it in the Docker image, because both are compressed. Installing an RPM should be relatively fast, and not having it in the Docker image means less management. If it were less than 100MB, it would be justifiable, but at 2GB, it's not.

> Just curious if I should expect ~750 kB/s download from

I got 10MBps from the office over 1gbps and WiFi. From Linode (cloud provider) I got 60MBps.. The server is connected at 1gbps so it should be able to burst high. I have been noticing pretty serious throttling from my cable provider (Comcast) over the last months from places like GitHub and Red Hat mirrors, which used to be blazingly fast.

**Comment by zbeekman** [comment]
> I got 10MBps from the office over 1gbps and WiFi. From Linode (cloud provider) I got 60MBps.. The server is connected at 1gbps so it should be able to burst high. I have been noticing pretty serious throttling from my cable provider (Comcast) over the last months from places like GitHub and Red Hat mirrors, which used to be blazingly fast.

Strange... our ISP in the office I work from is Cogent (some sort of corporate ISP, I guess). But throttling to < 1Mb/s seems extreme. For now I think the easiest solution will be to just build a local minimal TAU Commander installation.

Let's close this, since I think the issues are mostly resolved. It looks like PyOPALtools is still causing CI failures, but that doesn't seem to impact our work at all.
