### ISSUE TITLE
Can't run with vagrant

### ISSUE THREAD

**Issue by zbeekman** [radiasoft/container-beamsim-part1#3]
Hi @robnagler,

I'm trying to get TAU Commander installed inside the docker image/VM, because I've been striking out installing it via a docker script; the user of beamsim-part1 seems to be in a strange environment. Maybe their default shell is /bin/sh? Also, it seems that TAU Commander cannot download remote resources when configuring measurements. It tries to use cURL or wget, but both fail. So I tried to launch and interactive session with beamsim-part1 via vagrant, but this fails:

```
curl radia.run | bash -s beamsim-part1 vagrant
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   312  100   312    0     0    477      0 --:--:-- --:--:-- --:--:--   477
Log: /Users/ibeekman/Sandbox/zgoubi/radia-run-install.log
curl -L -s -S https://raw.githubusercontent.com/radiasoft/download/master/installers/beamsim-part1/radiasoft-download.sh
radiasoft-download.sh: no #! at start of file: /var/tmp/radia-run-90354-6764/20180815124606-radiasoft-download.sh
If you don't know what to do, please contact support@radiasoft.net.
```

Here is the log: 
[radia-run-install.log.txt](https://github.com/radiasoft/container-beamsim-part1/files/2291008/radia-run-install.log.txt)

Thanks!

**Comment by robnagler** [comment]
`curl radia.run | bash -s beamsim-part1 vagrant` is not correct. Is this mentioned in the documentation?

If you want to run the beamsim container (superset of beamsim-part1), you can say:

```sh
curl radia.run | bash -s beamsim
```

Instructions will be output for how to run the container interactively with the local directory mounted.

Of course, you can always just say:

```sh
docker run -it radiasoft/beamsim-part1
```

This will start the container as root. You can then `su - vagrant` to get the build environment as a the "run" user.

**Comment by zbeekman** [comment]
> curl radia.run | bash -s beamsim-part1 vagrant is not correct. Is this mentioned in the documentation?

Which documentation? It's a bit tough to know where to look with the myriad of repositories. It wasn't explicitly mentioned in Radiasoft/download, I was admittedly extrapolating which is dangerous.

> Of course, you can always just say:
> 
> docker run -it radiasoft/beamsim-part1
> This will start the container as root. You can then su - vagrant to get the build environment as a the "run" user.

Ah, great, yes that will do for now. Thanks!
